
---
name: monitor_event1
pack: monitor
description: Sample rule firing on monitor.event1.
enabled: true

trigger:
  type: "core.st2.webhook"
  parameters:
    url: "monitor"

criteria:
  trigger.body.name:
    type: "equals"
    pattern: "Rules"

action:
  ref: core.echo
  parameters:
    message: "{{trigger}"
