---
name: on_hello_event1
pack: monitor
description: Sample rule firing on monitor.event1.
enabled: true
trigger:
    type: monitor.event1
action:
    ref: monitor.greet
    parameters:
        greeting: Yo
